name: Matrix Configuration

on:
    push:
    workflow_dispatch:

jobs:
    deploy:
        strategy:
            fail-fast: false
            max-parallel: 2
            matrix:
                 os: [ubuntu-latest, windows-latest, ubuntu-22.04]
                 images: [hello-world, alpine]
                 exclude:
                   - os: windows-latest
                     images: alpine
                 include:
                   - os: windows-latest
                     images: amd64/alpine
        runs-on: ${{ matrix.os }}
        steps:
        - name: Echo Matrix Values
          run: docker info
        
        - name: Run Images on ${{ matrix.os }}
          run: |
            echo "Running on OS: ${{ matrix.os }}"
