name: Generate ASCII Artwork

on: 
    push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
            - name: Install Cowsat Program
              run: sudo apt-get install -y cowsay
  
            - name: Execute Cosway Command
              run: cowsay -f dragon "Run for cover, I am a DRAGON...RAWR!" >> dragon.txt
  
            - name: Upload Dragon Text File
              uses: actions/upload-artifact@v5
              with:
                name: dragon-text-file
                path: dragon.txt

    test_job_2:
        needs: build_job_1
        runs-on: ubuntu-latest
        steps:
            - name: Upload Dragon Text File
              uses: actions/download-artifact@v5
              with:
                name: dragon-text-file
                path: dragon.txt

            - name: Test File Exists
              run: grep -i "dragon" dragon.txt
    
    deploy_job_3:
        needs: [test_job_2]
        runs-on: ubuntu-latest
        steps:
            - name: Upload Dragon Text File
              uses: actions/download-artifact@v5
              with:
                name: dragon-text-file
                path: dragon.txt
                
            - name: Deploy - Display File Content
              run: cat dragon.txt

            - name: Deploy
              run: echo Deploying ... .. .
