name: Exploring Workflow Dispath

on:
  workflow_dispatch:
#   schedule:
#     - cron: "*/59 * * * *"
  push:
    # branches-ignore:
    #   - feature/*           # feature/add-music, feature/updates
    #   - test/**             # test/ui/index,. test/checkpout/payment
    branches:
      - main
      - '!feature/*'
  pull_request:
    types:
      - opened
      - closed
    paths-ignore:
        README.MD
    branches:
        - main


jobs:
    hello:
        runs-on: 
            ubuntu-latest
        steps:
        - run: echo this workflow/job/step is executed for event type - ${{ github.event_name}}